---
assignments:
  assignMPRAworkshop:
    bc_length: 15
    alignment_tool:
        tool: bwa
        configs:
          sequence_length:
            min: 195
            max: 205
          alignment_start:
            min: 14
            max: 16
experiments:
  experimentMPRAworkshop:
    bc_length: 15
    umi_length: 16
    data_folder: example_data/counts
    experiment_file: example_data/experiment.csv
    assignments:
      MPRAworkshop:
        type: config
        assignment_name: assignMPRAworkshop
        assignment_config: default
    label_file: example_data/design/workshop_labels.tsv
    configs:
      default: {}
      tutorialConfig:
        filter:
          bc_threshold: 5
          DNA:
            min_counts: 1
          RNA:
            min_counts: 1
