---
version: "0.5"
assignments:
  assignMPRAworkshop:
    bc_length: 15
    alignment_tool:
        # split_number: 30 # number of files fastq should be split for parallelization
        tool: bbmap
        configs:
          sequence_length: 200
          alignment_start: 1
    FW:
      - example_data/assignment/assoc_fwd.fastq.gz
    BC:
      - example_data/assignment/assoc_bc.fastq.gz
    REV:
      - example_data/assignment/assoc_rev.fastq.gz
    design_file: example_data/design/workshop_design.fa
    configs:
      default: {}
