---
version: "0.5"
experiments:
  experimentMPRAworkshop:
    bc_length: 15
    umi_length: 16
    data_folder: example_data/counts
    experiment_file: example_data/experiment.csv
    assignments:
      MPRAworkshop:
        type: file
        assignment_file: example_data/assignment/assignment_barcodes.default.tsv.gz
    label_file: example_data/design/workshop_labels.tsv
    configs:
      default: {}
      tutorialConfig:
        filter:
          bc_threshold: 5
          DNA:
            min_counts: 1
          RNA:
            min_counts: 1
