global:
  assignments:
    split_number: 30
assignments:
  assignMPRAworkshop:
    bc_length: 15
    sequence_length:
      min: 195
      max: 205
    alignment_start:
      min: 14
      max: 16
    min_mapping_quality: 1
    FW:
      - example_data/assignment/assoc_fwd.fastq.gz
    BC:
      - example_data/assignment/assoc_bc.fastq.gz
    REV:
      - example_data/assignment/assoc_rev.fastq.gz
    reference: example_data/design/workshop_design.fa
    configs:
      standardConfig:
        min_support: 3
        fraction: 0.7
experiments:
  workshop_data:
    bc_length: 15
    umi_length: 16
    data_folder: example_data/counts
    experiment_file: example_data/experiment.csv
    demultiplex: false
    assignments:
      MPRAworkshop:
        type: config
        assignment_name: assignMPRAworkshop
        assignment_config: standardConfig
    design_file: example_data/design/workshop_design.fa
    label_file: example_data/design/workshop_labels.tsv
    configs:
      tutorialConfig:
        filter:
          bc_threshold: 5
          DNA:
            min_counts: 1
          RNA:
            min_counts: 1

