---
    name: Build and Push Docker Image
    
    on: workflow_dispatch
    
    jobs:
      build-and-push:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          
          - name: Read version from file
            id: read_version
            run: |
              export $(cat versions.txt | xargs)
              echo "MPRASNAKEFLOW_VERSION=$MPRASNAKEFLOW_VERSION" >> $GITHUB_ENV
              echo "SNAKEMAKE_VERSION=$SNAKEMAKE_VERSION" >> $GITHUB_ENV
    
    
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
    
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Build and push Docker image
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              tags: visze/mprasnakeflow_tutorial:${{ env.MPRASNAKEFLOW_VERSION }}
              build-args: |
                  MPRASNAKEFLOW_VERSION=env.MPRASNAKEFLOW_VERSION
                  SNAKEMAKE_VERSION=env.SNAKEMAKE_VERSION
